// https://github.com/dariusk/corpora/blob/master/data/objects/objects.json
export const objects = {
    animals: [
        "aardvark",
        "albatross",
        "alligator",
        "alpaca",
        "ant",
        "anteater",
        "antelope",
        "ape",
        "armadillo",
        "baboon",
        "badger",
        "barracuda",
        "bat",
        "bear",
        "beaver",
        "bee",
        "bison",
        "boar",
        "buffalo",
        "butterfly",
        "camel",
        "capybara",
        "caribou",
        "cassowary",
        "cat",
        "caterpillar",
        "cattle",
        "chamois",
        "cheetah",
        "chicken",
        "chimpanzee",
        "chinchilla",
        "chough",
        "clam",
        "cobra",
        "cockroach",
        "cod",
        "cormorant",
        "coyote",
        "crab",
        "crane",
        "crocodile",
        "crow",
        "curlew",
        "deer",
        "dinosaur",
        "dog",
        "dogfish",
        "dolphin",
        "donkey",
        "dotterel",
        "dove",
        "dragonfly",
        "duck",
        "dugong",
        "dunlin",
        "eagle",
        "echidna",
        "eel",
        "eland",
        "elephant",
        "elephant-seal",
        "elk",
        "emu",
        "falcon",
        "ferret",
        "finch",
        "fish",
        "flamingo",
        "fly",
        "fox",
        "frog",
        "gaur",
        "gazelle",
        "gerbil",
        "giant-panda",
        "giraffe",
        "gnat",
        "gnu",
        "goat",
        "goose",
        "goldfinch",
        "goldfish",
        "gorilla",
        "goshawk",
        "grasshopper",
        "grouse",
        "guanaco",
        "guinea-fowl",
        "guinea-pig",
        "gull",
        "hamster",
        "hare",
        "hawk",
        "hedgehog",
        "heron",
        "herring",
        "hippopotamus",
        "hornet",
        "horse",
        "human",
        "hummingbird",
        "hyena",
        "ibex",
        "ibis",
        "jackal",
        "jaguar",
        "jay",
        "jellyfish",
        "kangaroo",
        "kingfisher",
        "koala",
        "komodo-dragon",
        "kookabura",
        "kouprey",
        "kudu",
        "lapwing",
        "lark",
        "lemur",
        "leopard",
        "lion",
        "llama",
        "lobster",
        "locust",
        "loris",
        "louse",
        "lyrebird",
        "magpie",
        "mallard",
        "manatee",
        "mandrill",
        "mantis",
        "marten",
        "meerkat",
        "mink",
        "mole",
        "mongoose",
        "monkey",
        "moose",
        "mouse",
        "mosquito",
        "mule",
        "narwhal",
        "newt",
        "nightingale",
        "octopus",
        "okapi",
        "opossum",
        "oryx",
        "ostrich",
        "otter",
        "owl",
        "ox",
        "oyster",
        "panther",
        "parrot",
        "partridge",
        "peafowl",
        "pelican",
        "penguin",
        "pheasant",
        "pig",
        "pigeon",
        "polar-bear",
        "pony",
        "porcupine",
        "porpoise",
        "prairie-dog",
        "quail",
        "quelea",
        "quetzal",
        "rabbit",
        "raccoon",
        "rail",
        "ram",
        "rat",
        "raven",
        "red-deer",
        "red-panda",
        "reindeer",
        "rhinoceros",
        "rook",
        "salamander",
        "salmon",
        "sand-dollar",
        "sandpiper",
        "sardine",
        "scorpion",
        "sea-lion",
        "sea-urchin",
        "seahorse",
        "seal",
        "shark",
        "sheep",
        "shrew",
        "skunk",
        "snail",
        "snake",
        "sparrow",
        "spider",
        "spoonbill",
        "squid",
        "squirrel",
        "starling",
        "stingray",
        "stinkbug",
        "stork",
        "swallow",
        "swan",
        "tapir",
        "tarsier",
        "termite",
        "tiger",
        "toad",
        "trout",
        "turkey",
        "turtle",
        "vicuña",
        "viper",
        "vulture",
        "wallaby",
        "walrus",
        "wasp",
        "water-buffalo",
        "weasel",
        "whale",
        "wolf",
        "wolverine",
        "wombat",
        "woodcock",
        "woodpecker",
        "worm",
        "wren",
        "yak",
        "zebra"
    ],

    colors: [
        "Maroon",
        "Violet",
        "Mauv",
        "Blue",
        "Turquoise",
        "Goldenrod",
        "Red",
        "Blue",
        "Red",
        "Maroon",
        "Pink",
        "Maroon",
        "Pink",
        "Aquamarine",
        "Fuscia",
        "Orange",
        "Goldenrod",
        "Puce",
        "Indigo",
        "Khaki",
        "Purple",
        "Fuscia",
        "Green",
        "Red",
        "Indigo",
        "Puce",
        "Indigo",
        "Blue",
        "Orange",
        "Crimson",
        "Yellow",
        "Orange",
        "Green",
        "Turquoise",
        "Turquoise",
        "Maroon",
        "Puce",
        "Pink",
        "Orange",
        "Pink",
        "Red",
        "Violet",
        "Violet",
        "Yellow",
        "Blue",
        "Crimson",
        "Khaki",
        "Maroon",
        "Yellow",
        "Purple",
        "Red",
        "Puce",
        "Crimson",
        "Violet",
        "Puce",
        "Purple",
        "Goldenrod",
        "Teal",
        "Fuscia",
        "Crimson",
        "Violet",
        "Aquamarine",
        "Goldenrod",
        "Fuscia",
        "Mauv",
        "Red",
        "Yellow",
        "Puce",
        "Pink",
        "Goldenrod",
        "Violet",
        "Goldenrod",
        "Blue",
        "Turquoise",
        "Mauv",
        "Violet",
        "Green",
        "Goldenrod",
        "Teal",
        "Red",
        "Maroon",
        "Aquamarine",
        "Goldenrod",
        "Goldenrod",
        "Indigo",
        "Blue",
        "Red",
        "Fuscia",
        "Pink",
        "Pink",
        "Indigo",
        "Crimson",
        "Pink",
        "Turquoise",
        "Indigo",
        "Red",
        "Fuscia",
        "Goldenrod",
        "Turquoise",
        "Purple",
    ],

    countries: [
        "Cuba",
        "China",
        "Finland",
        "Syria",
        "Indonesia",
        "Serbia",
        "Philippines",
        "Czech Republic",
        "China",
        "Kosovo",
        "Indonesia",
        "Argentina",
        "France",
        "Serbia",
        "Russia",
        "Japan",
        "Yemen",
        "China",
        "Indonesia",
        "Iran",
        "Indonesia",
        "China",
        "United States",
        "China",
        "United States",
        "Thailand",
        "Indonesia",
        "United States",
        "China",
        "Indonesia",
        "France",
        "Philippines",
        "China",
        "Costa Rica",
        "Mali",
        "United Kingdom",
        "China",
        "Portugal",
        "Portugal",
        "Greece",
        "Russia",
        "Sweden",
        "Philippines",
        "China",
        "Sweden",
        "Malta",
        "France",
        "Belarus",
        "Costa Rica",
        "Portugal",
        "Indonesia",
        "Philippines",
        "Russia",
        "Thailand",
        "Finland",
        "Portugal",
        "China",
        "Uzbekistan",
        "Canada",
        "Portugal",
        "Russia",
        "Greece",
        "Colombia",
        "Indonesia",
        "Thailand",
        "Venezuela",
        "Indonesia",
        "Peru",
        "Mexico",
        "Poland",
        "Indonesia",
        "Madagascar",
        "China",
        "Philippines",
        "Philippines",
        "China",
        "Indonesia",
        "Mexico",
        "China",
        "Azerbaijan",
        "Japan",
        "China",
        "China",
        "Bangladesh",
        "China",
        "Indonesia",
        "Micronesia",
        "Czech Republic",
        "China",
        "China",
        "Cambodia",
        "Mauritius",
        "Philippines",
        "France",
        "Panama",
        "China",
        "Philippines",
        "Colombia",
        "China",
        "Indonesia",
    ],

    cars: [
        "Ford",
        "Honda",
        "Lexus",
        "Toyota",
        "Ford",
        "Volkswagen",
        "Honda",
        "Pontiac",
        "Ford",
        "Chevrolet",
        "Land Rover",
        "BMW",
        "GMC",
        "Mazda",
        "Kia",
        "Infiniti",
        "Land Rover",
        "Chevrolet",
        "Chevrolet",
        "Volkswagen",
        "Mazda",
        "Chevrolet",
        "Jaguar",
        "Volkswagen",
        "Chevrolet",
        "Audi",
        "Chevrolet",
        "Volkswagen",
        "Dodge",
        "Chevrolet",
        "Buick",
        "Honda",
        "Chevrolet",
        "Chevrolet",
        "Jeep",
        "Suzuki",
        "Audi",
        "Cadillac",
        "Honda",
        "GMC",
        "Acura",
        "BMW",
        "Audi",
        "Ford",
        "Pontiac",
        "Mazda",
        "Lexus",
        "Lincoln",
        "Chevrolet",
        "Hyundai",
        "GMC",
        "GMC",
        "Morgan",
        "Chevrolet",
        "Chevrolet",
        "Dodge",
        "Mitsubishi",
        "Chevrolet",
        "Mercury",
        "BMW",
        "Jeep",
        "Oldsmobile",
        "Lincoln",
        "Chevrolet",
        "GMC",
        "Nissan",
        "Mercedes-Benz",
        "Jeep",
        "Eagle",
        "Toyota",
        "Chevrolet",
        "GMC",
        "GMC",
        "Toyota",
        "Lexus",
        "GMC",
        "Ford",
        "Mercury",
        "Chevrolet",
        "Hyundai",
        "Ford",
        "Chevrolet",
        "Mercedes-Benz",
        "Isuzu",
        "Subaru",
        "Mercedes-Benz",
        "Cadillac",
        "Toyota",
        "Jaguar",
        "Mazda",
        "Hyundai",
        "Acura",
        "Honda",
        "Mercury",
        "Volkswagen",
        "Isuzu",
        "Mitsubishi",
        "Cadillac",
        "Oldsmobile",
    ],

    person: [
        'male',
        'female',
        'ladies',
        'gents',
        'gentlemen',
        'boy',
        'girl',
        'man',
        'woman'
    ],

    fruits: [
        "apple",
        "apricot",
        "avocado",
        "banana",
        "bell pepper",
        "bilberry",
        "blackberry",
        "blackcurrant",
        "blood orange",
        "blueberry",
        "boysenberry",
        "breadfruit",
        "canary melon",
        "cantaloupe",
        "cherimoya",
        "cherry",
        "chili pepper",
        "clementine",
        "cloudberry",
        "coconut",
        "cranberry",
        "cucumber",
        "currant",
        "damson",
        "date",
        "dragonfruit",
        "durian",
        "eggplant",
        "elderberry",
        "feijoa",
        "fig",
        "goji berry",
        "gooseberry",
        "grape",
        "grapefruit",
        "guava",
        "honeydew",
        "huckleberry",
        "jackfruit",
        "jambul",
        "jujube",
        "kiwi fruit",
        "kumquat",
        "lemon",
        "lime",
        "loquat",
        "lychee",
        "mandarine",
        "mango",
        "mulberry",
        "nectarine",
        "nut",
        "olive",
        "orange",
        "papaya",
        "passionfruit",
        "peach",
        "pear",
        "persimmon",
        "physalis",
        "pineapple",
        "plum",
        "pomegranate",
        "pomelo",
        "purple mangosteen",
        "quince",
        "raisin",
        "rambutan",
        "raspberry",
        "redcurrant",
        "rock melon",
        "salal berry",
        "satsuma",
        "star fruit",
        "strawberry",
        "tamarillo",
        "tangerine",
        "tomato",
        "ugli fruit",
        "watermelon"
    ],

    bodyParts: [
        "ankle",
        "arm",
        "back",
        "belly",
        "bottom",
        "breast",
        "buttocks",
        "calf",
        "cheek",
        "chin",
        "ear",
        "elbow",
        "eye",
        "eyebrow",
        "eyelash",
        "finger",
        "fist",
        "foot",
        "forearm",
        "forehead",
        "hair",
        "hand",
        "head",
        "hip",
        "knee",
        "leg",
        "lip",
        "lower leg",
        "mouth",
        "neck",
        "nose",
        "nostril",
        "shoulder",
        "thigh",
        "thumb",
        "toe",
        "tongue",
        "tooth",
        "upper arm",
        "waist",
        "wrist"
    ],

    objects: [
        "CD",
        "Christmas ornament",
        "acorn",
        "apple",
        "bag",
        "bag of cotton balls",
        "bag of popcorn",
        "bag of rubber bands",
        "ball of yarn",
        "balloon",
        "banana",
        "bananas",
        "bandana",
        "bangle bracelet",
        "bar of soap",
        "baseball",
        "baseball bat",
        "baseball hat",
        "basketball",
        "beaded bracelet",
        "beaded necklace",
        "bed",
        "beef",
        "bell",
        "belt",
        "blouse",
        "blowdryer",
        "bonesaw",
        "book",
        "book of jokes",
        "book of matches",
        "bookmark",
        "boom box",
        "bottle",
        "bottle cap",
        "bottle of glue",
        "bottle of honey",
        "bottle of ink",
        "bottle of lotion",
        "bottle of nail polish",
        "bottle of oil",
        "bottle of paint",
        "bottle of perfume",
        "bottle of pills",
        "bottle of soda",
        "bottle of sunscreen",
        "bottle of syrup",
        "bottle of water",
        "bouquet of flowers",
        "bow",
        "bow tie",
        "bowl",
        "box",
        "box of Q-tips",
        "box of baking soda",
        "box of chalk",
        "box of chocolates",
        "box of crayons",
        "box of markers",
        "box of tissues",
        "bracelet",
        "bread",
        "broccoli",
        "brush",
        "buckle",
        "butter knife",
        "button",
        "camera",
        "can of beans",
        "can of chili",
        "can of peas",
        "can of whipped cream",
        "candle",
        "candlestick",
        "candy bar",
        "candy cane",
        "candy wrapper",
        "canteen",
        "canvas",
        "car",
        "card",
        "carrot",
        "carrots",
        "cars",
        "carton of ice cream",
        "cat",
        "catalogue",
        "cell phone",
        "cellphone",
        "cement stone",
        "chain",
        "chair",
        "chalk",
        "chapter book",
        "check book",
        "chenille stick",
        "chicken",
        "children's book",
        "chocolate",
        "class ring",
        "clay pot",
        "clock",
        "clothes",
        "clothes pin",
        "coffee mug",
        "coffee pot",
        "comb",
        "comic book",
        "computer",
        "conditioner",
        "container of pudding",
        "cookie jar",
        "cookie tin",
        "cork",
        "couch",
        "cow",
        "cowboy hat",
        "craft book",
        "credit card",
        "crow",
        "crowbar",
        "cucumber",
        "cup",
        "dagger",
        "deodorant",
        "desk",
        "dictionary",
        "dog",
        "dolphin",
        "domino set",
        "door",
        "dove",
        "drawer",
        "drill press",
        "egg",
        "egg beater",
        "egg timer",
        "empty bottle",
        "empty jar",
        "empty tin can",
        "eraser",
        "extension cord",
        "eye liner",
        "face wash",
        "fake flowers",
        "feather",
        "feather duster",
        "few batteries",
        "fish",
        "fishing hook",
        "flag",
        "flashlight",
        "floor",
        "flowers",
        "flyswatter",
        "food",
        "football",
        "fork",
        "fridge",
        "frying pan",
        "game CD",
        "game cartridge",
        "garden spade",
        "giraffe",
        "glass",
        "glasses",
        "glow stick",
        "grid paper",
        "grocery list",
        "hair brush",
        "hair clip",
        "hair pin",
        "hair ribbon",
        "hair tie",
        "hammer",
        "hamster",
        "hand bag",
        "hand fan",
        "hand mirror",
        "handbasket",
        "handful of change",
        "handheld game system",
        "hanger",
        "harmonica",
        "helmet",
        "house",
        "ice cream stick",
        "ice cube",
        "ice pick",
        "incense holder",
        "ipod",
        "ipod charger",
        "jar of jam",
        "jar of peanut butter",
        "jar of pickles",
        "jigsaw puzzle",
        "key",
        "key chain",
        "keyboard",
        "keychain",
        "keys",
        "kitchen knife",
        "knife",
        "lace",
        "ladle",
        "lamp",
        "lamp shade",
        "laser pointer",
        "leg warmers",
        "lemon",
        "letter opener",
        "light",
        "light bulb",
        "lighter",
        "lime",
        "lion",
        "lip gloss",
        "locket",
        "lotion",
        "magazine",
        "magnet",
        "magnifying glass",
        "map",
        "marble",
        "martini glass",
        "matchbook",
        "microphone",
        "milk",
        "miniature portrait",
        "mirror",
        "mobile phone",
        "model car",
        "money",
        "monitor",
        "mop",
        "mouse pad",
        "mp3 player",
        "multitool",
        "music CD",
        "nail",
        "nail clippers",
        "nail filer",
        "necktie",
        "needle",
        "notebook",
        "notepad",
        "novel",
        "ocarina",
        "orange",
        "outlet",
        "pack of cards",
        "package of crisp and crunchy edibles",
        "package of glitter",
        "packet of seeds",
        "pail",
        "paint brush",
        "paintbrush",
        "pair of binoculars",
        "pair of dice",
        "pair of earrings",
        "pair of glasses",
        "pair of handcuffs",
        "pair of knitting needles",
        "pair of rubber gloves",
        "pair of safety goggles",
        "pair of scissors",
        "pair of socks",
        "pair of sunglasses",
        "pair of tongs",
        "pair of water goggles",
        "panda",
        "pants",
        "paper",
        "paperclip",
        "pasta strainer",
        "pearl necklace",
        "pen",
        "pencil",
        "pencil holder",
        "pepper shaker",
        "perfume",
        "phone",
        "photo album",
        "picture frame",
        "piece of gum",
        "pillow",
        "pinecone",
        "plastic fork",
        "plate",
        "plush bear",
        "plush cat",
        "plush dinosaur",
        "plush dog",
        "plush frog",
        "plush octopus",
        "plush pony",
        "plush rabbit",
        "plush unicorn",
        "pocketknife",
        "pocketwatch",
        "pool stick",
        "pop can",
        "postage stamp",
        "puddle",
        "purse",
        "purse/bag",
        "quartz crystal",
        "quilt",
        "rabbit",
        "radio",
        "rat",
        "remote",
        "rhino",
        "ring",
        "rock",
        "roll of duct tape",
        "roll of gauze",
        "roll of masking tape",
        "roll of stickers",
        "roll of toilet paper",
        "rolling pin",
        "rope",
        "rubber band",
        "rubber duck",
        "rubber stamp",
        "rug",
        "rusty nail",
        "safety pin",
        "sailboat",
        "salt shaker",
        "sand paper",
        "sandal",
        "sandglass",
        "scallop shell",
        "scarf",
        "scotch tape",
        "screw",
        "screwdriver",
        "seat belt",
        "shampoo",
        "shark",
        "sharpie",
        "shawl",
        "sheep",
        "sheet of paper",
        "shirt",
        "shirt button",
        "shoe lace",
        "shoes",
        "shopping bag",
        "shovel",
        "sidewalk",
        "sketch pad",
        "slipper",
        "small pouch",
        "snail shell",
        "snowglobe",
        "soap",
        "soccer ball",
        "socks",
        "sofa",
        "spatula",
        "speakers",
        "spectacles",
        "spice bottle",
        "sponge",
        "spool of ribbon",
        "spool of string",
        "spool of thread",
        "spool of wire",
        "spoon",
        "spring",
        "squirrel",
        "squirt gun",
        "statuette",
        "steak knife",
        "stick",
        "stick of incense",
        "sticker book",
        "sticky note",
        "stockings",
        "stop sign",
        "straw",
        "street lights",
        "sun glasses",
        "sword",
        "table",
        "tea cup",
        "tea pot",
        "teddies",
        "television",
        "tennis ball",
        "tennis racket",
        "thermometer",
        "thimble",
        "thread",
        "tiger",
        "tire swing",
        "tissue box",
        "toe ring",
        "toilet",
        "toilet paper tube",
        "tomato",
        "tooth pick",
        "toothbrush",
        "toothpaste",
        "toothpick",
        "towel",
        "toy boat",
        "toy car",
        "toy plane",
        "toy robot",
        "toy soldier",
        "toy top",
        "trash bag",
        "tree",
        "trucks",
        "tube of lip balm",
        "tube of lipstick",
        "turtle",
        "tv",
        "tweezers",
        "twister",
        "umbrella",
        "vase",
        "video games",
        "wallet",
        "washcloth",
        "washing machine",
        "watch",
        "water",
        "water bottle",
        "wedding ring",
        "whale",
        "whip",
        "whistle",
        "white out",
        "window",
        "wine glass",
        "wireless control",
        "wishbone",
        "wooden spoon",
        "word search",
        "wrench",
        "wristwatch",
        "zebra",
        "zipper"
    ],

    sports: [
        "10K run",
        "16-inch softball",
        "43-Man Squamish",
        "5K run",
        "ATV racing",
        "Abseiling",
        "Acro sports",
        "Acrobatic gymnastics",
        "Aerobatics",
        "Aerobic gymnastics",
        "Aid climbing",
        "Aiki-jūjutsu",
        "Aikido",
        "Air hockey",
        "Air racing",
        "Air sports",
        "Airsoft",
        "Aizkolaritza",
        "All-terrain vehicle competition",
        "Alpine skiing",
        "Amateur wrestling",
        "American flag rugby",
        "American football",
        "American handball",
        "Angling",
        "Apnoea finswimming",
        "Aquathlon",
        "Archery",
        "Arena football",
        "Arm wrestling",
        "Artistic billiards",
        "Artistic cycling",
        "Artistic gymnastics",
        "Artistic pool",
        "Association football",
        "Australian football",
        "Australian handball",
        "Austus",
        "Auto Race",
        "Auto racing",
        "Autocross",
        "Autograss",
        "Axe throwing",
        "BASE jumping",
        "BMX",
        "Ba game",
        "Backgammon",
        "Backpacking",
        "Backstroke",
        "Badminton",
        "Bagatelle",
        "Baguazhang",
        "Balance beam",
        "Balkline and straight rail",
        "Ball badminton",
        "Ball hockey",
        "Ball",
        "Ball-over-net games",
        "Bando",
        "Bandy",
        "Banger racing",
        "Bank pool",
        "Banzai skydiving",
        "Bar billiards",
        "Bareback Bronc Riding",
        "Barrel Racing",
        "Barrel jumping",
        "Barrel racing",
        "Bartitsu",
        "Baseball pocket billiards",
        "Baseball",
        "Basketball",
        "Basque pelota",
        "Basque traditional weightlifting",
        "Bat and trap",
        "Baton twirling",
        "Battōjutsu",
        "Beach basketball",
        "Beach handball",
        "Beach rugby",
        "Beach soccer",
        "Beach tennis",
        "Beach volleyball",
        "Beagling",
        "Beer Pong",
        "Benchrest shooting",
        "Biathlon",
        "Bicycle polo",
        "Bifins",
        "Big game hunting",
        "Big-game fishing",
        "Biribol",
        "Blackball",
        "Board sports",
        "Board track racing",
        "Bobsleigh",
        "Bocce volo",
        "Bocce",
        "Boccia",
        "Bodyboarding",
        "Bodybuilding",
        "Boffer fighting",
        "Bokator",
        "Bolas criollas",
        "Boli Khela",
        "Bossaball",
        "Bottle pool",
        "Bouldering",
        "Boule Lyonnaise",
        "Boules",
        "Bowling",
        "Bowlliards",
        "Bowls",
        "Box lacrosse",
        "Boxing",
        "Brazilian jiu-jitsu",
        "Breakaway Roping",
        "Breaststroke",
        "British baseball",
        "British bulldogs",
        "Bronc Riding",
        "Broomball",
        "Brännboll",
        "Bujinkan",
        "Bullriding",
        "Bumper pool",
        "Bungee jumping",
        "Bunnock",
        "Bushwhacking",
        "Butterfly stroke",
        "Butts Up",
        "Buzkashi",
        "Caid",
        "Calcio Fiorentino",
        "Calf Roping",
        "Calva",
        "Calvinball",
        "Cammag",
        "Camogie",
        "Campdrafting",
        "Canadian football",
        "Canoe polo",
        "Canoeing",
        "Canyoning",
        "Capoeira",
        "Capture the flag",
        "Card stacking",
        "Carom billiards",
        "Casterboarding",
        "Casting",
        "Catch games",
        "Catch wrestling",
        "Cestoball",
        "Chariot racing",
        "Charreada",
        "Checkers",
        "Cheerleading",
        "Chess boxing",
        "Chicago",
        "Chilean rodeo",
        "Chinese handball",
        "Chinlone",
        "Choi Kwang-Do",
        "Cirit",
        "Clay pigeon shooting",
        "Cliff diving",
        "Climbing",
        "Club",
        "Cluster ballooning",
        "Cnapan",
        "Coastal and ocean rowing",
        "Coasteering",
        "Cockfighting",
        "Collar-and-elbow",
        "Competitive dancing",
        "Competitive eating",
        "Competitive swimming",
        "Composite rules shinty-hurling",
        "Connect Four",
        "Cornhole",
        "Cornish hurling",
        "Cornish wrestling",
        "Cowboy action shooting",
        "Cowboy polo",
        "Cowboy",
        "Creeking",
        "Cribbage",
        "Cricket",
        "Croquet",
        "Cross country",
        "Cross-country mountain biking",
        "Cross-country rally",
        "Cross-country running",
        "Cross-country skiing",
        "CrossFit",
        "Cue sports",
        "Cuju",
        "Curling",
        "Cushion caroms",
        "Cutthroat",
        "Cutting",
        "Cycle polo",
        "Cycle speedway",
        "Cycling",
        "Cyclo-cross",
        "Czech handball",
        "Dancesport",
        "Danish longball",
        "Darts",
        "Deaf basketball",
        "Decathlon",
        "Deep-water soloing",
        "Deer hunting",
        "Demolition derby",
        "Desert racing",
        "Dice stacking",
        "Dinghy sailing",
        "Dirt jumping",
        "Dirt track racing",
        "Disc dog",
        "Disc golf",
        "Discus",
        "Diving",
        "Dodge disc",
        "Dodgeball",
        "Dominoes",
        "Double disc court",
        "Downhill mountain biking",
        "Drag boat racing",
        "Drag racing",
        "Dragon boat racing",
        "Dressage",
        "Drifting",
        "Duathlon",
        "Dumog",
        "Eclipse Ball",
        "Egg and spoon race",
        "Egyptian stick fencing",
        "Eight-ball",
        "Eight-man football",
        "Ekiden",
        "Elephant polo",
        "Elle",
        "Endurance racing",
        "Endurance riding",
        "Enduro",
        "English billiards",
        "English pleasure",
        "English school games",
        "Episkyros",
        "Equestrian vaulting",
        "Equitation",
        "Eskrima",
        "Eton College",
        "Eton Fives",
        "Eton wall game",
        "Eventing",
        "Extreme ironing",
        "F1 powerboat racing",
        "Fast-pitch softball",
        "Fastnet",
        "Fell running",
        "Fencing",
        "Ferret legging",
        "Field archery",
        "Field game",
        "Field handball",
        "Field hockey",
        "Field lacrosse",
        "Field target",
        "Fierljeppen",
        "Figure skating",
        "Fishing",
        "Fistball",
        "Five-a-side football",
        "Five-pins",
        "Fives",
        "Flag football",
        "Flight archery",
        "Floor",
        "Floorball",
        "Flutterguts",
        "Fly fishing",
        "Flyak",
        "Flying trapeze",
        "Folk wrestling",
        "Folkrace",
        "Foosball",
        "Footbag net",
        "Footbag",
        "Football tennis",
        "Football",
        "Footvolley",
        "Formula Libre",
        "Formula Student",
        "Formula racing",
        "Four square",
        "Four-ball",
        "Fox hunting",
        "Free running",
        "Free-style moto",
        "Freeboard",
        "Freeboating",
        "Freediving",
        "Freestyle BMX",
        "Freestyle footbag",
        "Freestyle football",
        "Freestyle motocross",
        "Freestyle skiing",
        "Freestyle swimming",
        "Freestyle wrestling",
        "Freestyle",
        "Frisian handball",
        "Frontenis",
        "Fujian White Crane",
        "Fullbore target rifle",
        "Futebol de Salão",
        "Futsal",
        "Ga-ga",
        "Gaelic football",
        "Gaelic handball",
        "Gateball",
        "Gatka",
        "Geocaching",
        "Gig racing",
        "Gliding",
        "Glima",
        "Goalball",
        "Goaltimate",
        "Goat Tying",
        "Golf",
        "Gouren",
        "Grand Prix motorcycle racing",
        "Grappling",
        "Grasstrack",
        "Greco-Roman wrestling",
        "Greek wrestling",
        "Gridiron football",
        "Gungdo",
        "Guts",
        "Gymkhana",
        "Gymnastics",
        "Haggis hurling",
        "Half marathon",
        "Hammer throw",
        "Hana Ichi Monme",
        "Handball",
        "Hang gliding",
        "Hapkido",
        "Hardball squash",
        "Hardcourt Bike Polo",
        "Hare coursing",
        "Harness racing",
        "Harpastum",
        "Harrow football",
        "Haxey Hood",
        "Headis",
        "Heptathlon",
        "Hide and seek",
        "High bar",
        "High jump",
        "High power rifle",
        "Highland games",
        "Hiking",
        "Hillclimbing",
        "Hockey",
        "Hojōjutsu",
        "Hoop",
        "Hooverball",
        "Hopper ballooning",
        "Hornussen",
        "Horse polo",
        "Horse racing",
        "Horseball",
        "Horseshoe throwing",
        "Horseshoe",
        "Horseshoes",
        "Hot Air Balloon Racing",
        "Hot air ballooning",
        "Hot box",
        "Human powered aircraft",
        "Hunter",
        "Hunter-jumpers",
        "Hurdles",
        "Hurling",
        "Hwa Rang Do",
        "Hybrid carom–pocket games",
        "Hybrid codes",
        "Hydroplane racing",
        "Iaidō",
        "Iaijutsu",
        "Ice climbing",
        "Ice dancing",
        "Ice fishing",
        "Ice hockey",
        "Ice racing",
        "Ice speedway",
        "Ice sports",
        "Ice yachting",
        "Icosathlon",
        "Immersion finswimming",
        "Individual medley",
        "Indoor archery",
        "Indoor cricket",
        "Indoor enduro",
        "Indoor field hockey",
        "Indoor football",
        "Indoor netball",
        "Indoor soccer",
        "Inline hockey",
        "Intercrosse",
        "International fronton",
        "International rules football",
        "Jai alai",
        "Janggi",
        "Javelin",
        "Jeet Kune Do",
        "Jet sprint boat racing",
        "Jeu de paume",
        "Jeu provençal",
        "Jianzi",
        "Jittejutsu",
        "Jogo do pau",
        "Jorkyball",
        "Jousting",
        "Judo",
        "Jugger",
        "Juggling",
        "Jujutsu",
        "Jumping",
        "Jōdō",
        "Jūkendō",
        "Kabaddi",
        "Kajukenbo",
        "Kalaripayattu",
        "Karate",
        "Kart racing",
        "Kayaking",
        "Keep away",
        "Keepie uppie",
        "Kelly pool",
        "Kemari",
        "Kendo",
        "Kenjutsu",
        "Kenpō",
        "Kho kho",
        "Ki-o-rahi",
        "Kick the can",
        "Kickball",
        "Kickboxing",
        "Kilikiti",
        "Killer",
        "Kin-Ball",
        "Kindred activities",
        "Kite buggy",
        "Kite fighting",
        "Kite flying",
        "Kite landboarding",
        "Kite sports",
        "Kiteboarding",
        "Kitesurfing",
        "Knattleikr",
        "Kneeboarding",
        "Knife throwing",
        "Korfball",
        "Krabi–krabong",
        "Krav Maga",
        "Kubb",
        "Kuk Sool Won",
        "Kumdo",
        "Kung fu",
        "Kurash",
        "Kyūdō",
        "Kyūjutsu",
        "La soule",
        "Lacrosse",
        "Ladies' Gaelic football",
        "Lancashire wrestling",
        "Land sailing",
        "Land speed records",
        "Land windsurfing",
        "Laser tag",
        "Legends car racing",
        "Lelo burti",
        "Lethwei",
        "Letterboxing",
        "Limited overs cricket",
        "Logrolling",
        "Long jump",
        "Longboarding",
        "Luge",
        "Lumberjack sports",
        "Mahjong",
        "Malla-yuddha",
        "Marathon",
        "Marching band",
        "Marine Corps Martial Arts Program",
        "Marn Grook",
        "Masters Football",
        "Masters Rugby League",
        "Matball",
        "Match play",
        "Matkot",
        "Medieval football",
        "Medley relay",
        "Mesoamerican ballgame",
        "Metallic silhouette shooting",
        "Metallic silhouette",
        "Metro footy",
        "Midget car racing",
        "Mini rugby",
        "Miniature Bull Riding",
        "Miniature golf",
        "Miniten",
        "Mixed climbing",
        "Mixed martial arts",
        "Mixed or hybrid",
        "Mob football",
        "Mod league",
        "Model aerobatics",
        "Model aircraft",
        "Modern Arnis",
        "Modern pentathlon",
        "Mongolian wrestling",
        "Monster truck",
        "Moscow broomball",
        "Motocross",
        "Motorboat racing",
        "Motorcycle drag racing",
        "Motorcycle racing",
        "Motorcycle speedway",
        "Motorized sports",
        "Mountain running",
        "Mountain unicycling",
        "Mountainboarding",
        "Mountaineering",
        "Muay Thai",
        "Mud bogging",
        "Mölkky",
        "Naginatajutsu",
        "Netball",
        "Newcomb ball",
        "Nguni stick-fighting",
        "Nine-a-side footy",
        "Nine-ball",
        "Nine-man football",
        "Ninjutsu",
        "Noodling",
        "Nordic combined",
        "Nordic skiing",
        "Northern Praying Mantis",
        "Novuss",
        "Object spinning",
        "Obstacle variations",
        "Off-road racing",
        "Off-roading",
        "Offshore powerboat racing",
        "Oina",
        "Okinawan kobudō",
        "Olympic weightlifting",
        "One Day International",
        "One-pocket",
        "Orienteering",
        "Outrigger canoeing",
        "Oztag",
        "Paddleboarding",
        "Padel",
        "Padiddling",
        "Paintball",
        "Pair skating",
        "Palant",
        "Paleta Frontón",
        "Pall mall",
        "Palla",
        "Pankration",
        "Papi fut",
        "Parachuting",
        "Paragliding",
        "Parallel bars",
        "Paralympic football",
        "Paralympic volleyball",
        "Paramotoring",
        "Parasailing",
        "Parkour",
        "Patball",
        "Pato",
        "Pehlwani",
        "Pelota mixteca",
        "Pencak Silat",
        "Pentathlon",
        "Personal water craft",
        "Peteca",
        "Pickleball",
        "Pickup truck racing",
        "Pitch and putt",
        "Plate spinning",
        "Platform tennis",
        "Pocket billiards",
        "Pole bending",
        "Pole climbing",
        "Pole vault",
        "Polo",
        "Polocrosse",
        "Pommel horse",
        "Pond hockey",
        "Popinjay",
        "Power hockey",
        "Powerbocking",
        "Powerchair Football",
        "Powered hang glider",
        "Powered paragliding",
        "Powerlifting",
        "Practical shooting",
        "Pradal serey",
        "Production car racing",
        "Professional wrestling",
        "Punchball",
        "Pétanque",
        "Qianball",
        "Quidditch",
        "RC racing",
        "Race of Champions",
        "Racewalking",
        "Racketlon",
        "Racquetball",
        "Racquets",
        "Rafting",
        "Rally raid",
        "Rallycross",
        "Rallying",
        "Real tennis",
        "Rec footy",
        "Red rover",
        "Reduced variants",
        "Regularity rally",
        "Reining",
        "Remote control",
        "Reversi",
        "Rhythmic gymnastics",
        "Ribbon",
        "Ring-goal",
        "Ringball",
        "Ringette",
        "Rink bandy",
        "Rinkball",
        "Riverboarding",
        "Road bicycle racing",
        "Road racing",
        "Road running",
        "Robot combat",
        "Rocball",
        "Rock climbing",
        "Rock fishing",
        "Rocket League",
        "Rodeo",
        "Rogaining",
        "Roller hockey",
        "Rope climbing",
        "Rope jumping",
        "Rope",
        "Roping",
        "Rossall Hockey",
        "Rotation",
        "Rounders",
        "Rowing",
        "Royal Shrovetide Football",
        "Rugby Fives",
        "Rugby football",
        "Rugby league nines",
        "Rugby league sevens",
        "Rugby league",
        "Rugby sevens",
        "Rugby tens",
        "Rugby union",
        "Running",
        "Russian pyramid",
        "Sack race",
        "Saddle Bronc Riding",
        "Sailing",
        "Samoa rules",
        "Sandboarding",
        "Sanshou",
        "Savate",
        "Schwingen",
        "Scootering",
        "Scrabble",
        "Scrub baseball",
        "Scuba diving",
        "Sea kayaking",
        "Segway polo",
        "Sepak takraw",
        "Seven-ball",
        "Shaolin Kung Fu",
        "Shidōkan Karate",
        "Shinty",
        "Shogi",
        "Shoot boxing",
        "Shootfighting",
        "Shooting",
        "Shorinji Kempo",
        "Short track motor racing",
        "Shot put",
        "Shotgun start",
        "Show jumping",
        "Shuai jiao",
        "Shuffleboard",
        "Shurikenjutsu",
        "Shōrin-ryū Shidōkan",
        "Sikaran",
        "Silambam",
        "Silat",
        "Single scull",
        "Single skating",
        "Sinuca brasileira",
        "Sipa",
        "Six-man football",
        "Six-red snooker",
        "Skateboarding",
        "Skater hockey",
        "Skee ball",
        "Skeet shooting",
        "Skeleton",
        "Ski flying",
        "Ski jumping",
        "Ski touring",
        "Skiboarding",
        "Skibob",
        "Skibobbing",
        "Skiing",
        "Skijoring",
        "Skimboarding",
        "Skins game",
        "Skirmish",
        "Skittles",
        "Skydiving",
        "Skyrunning",
        "Skysurfing",
        "Slacklining",
        "Slamball",
        "Sledge hockey",
        "Slot car racing",
        "Slow pitch",
        "Snooker plus",
        "Snooker",
        "Snorkelling",
        "Snow kiting",
        "Snow rugby",
        "Snow sports",
        "Snowboarding",
        "Snowkiting",
        "Snowmobile racing",
        "Snowshoe running",
        "Soap shoes",
        "Soft tennis",
        "Softball",
        "Spearfishing",
        "Speed golf",
        "Speed pool",
        "Speed skiing",
        "Speed-ball",
        "Speedball",
        "Speedminton",
        "Spongee",
        "Sport climbing",
        "Sport diving",
        "Sport fishing",
        "Sport kite",
        "Sport stacking",
        "Sporting clays",
        "Sports car racing",
        "Sprint car racing",
        "Sprint football",
        "Sprint",
        "Squash tennis",
        "Squash",
        "Squirt boating",
        "Ssireum",
        "Stacking",
        "Stand up paddle boarding",
        "Static trapeze",
        "Steeplechase",
        "Steer Roping",
        "Steer Wrestling",
        "Steinstossen",
        "Stick and ball games",
        "Stickball",
        "Stické",
        "Stihl Timbersports Series",
        "Still rings",
        "Stock car racing",
        "Stool ball",
        "Straight pool",
        "Street football",
        "Street hockey",
        "Street racing",
        "Street sports",
        "Street unicycling",
        "Street workout",
        "Streetball",
        "Streetboarding",
        "Streetluge",
        "Strength athletics",
        "Striking",
        "Stroke play",
        "Strongman",
        "Subak",
        "Subbuteo",
        "Sumo",
        "Superbike racing",
        "Supercross",
        "Supermoto",
        "Superside",
        "Supersport racing",
        "Sur-papakh",
        "Surf fishing",
        "Surf kayaking",
        "Surface finswimming",
        "Surfboat",
        "Surfing",
        "Swamp football",
        "Swimming",
        "Sword fighting",
        "Synchronized swimming",
        "Systema",
        "Sōjutsu",
        "T'ai chi ch'uan",
        "TT racing",
        "Table Sports",
        "Table football",
        "Table hockey",
        "Table sports",
        "Table tennis",
        "Taekkyeon",
        "Taekwondo",
        "Tag games",
        "Tag rugby",
        "Tag",
        "Taidō",
        "Tang Soo Do",
        "Target archery",
        "Target shooting",
        "Tchoukball",
        "Team Roping",
        "Team handball",
        "Team penning",
        "Team play",
        "Tee-ball",
        "Telemark skiing",
        "Ten-ball",
        "Tennikoit",
        "Tennis polo",
        "Tennis",
        "Tent pegging",
        "Test cricket",
        "Tetherball",
        "Tetrathlon",
        "Three sided football",
        "Three-ball",
        "Three-cushion",
        "Three-legged race",
        "Throwball",
        "Throwing",
        "Thumb wrestling",
        "Time attack",
        "Toboggan",
        "Toe wrestling",
        "Torball",
        "Touch football",
        "Touch rugby",
        "Touring car racing",
        "Tournament of Knights",
        "Tower running",
        "Town ball",
        "Track cycling",
        "Track racing",
        "Tractor pulling",
        "Traditional climbing",
        "Trail running",
        "Trampolining",
        "Trap shooting",
        "Trapeze",
        "Trial",
        "Triathlon",
        "Trick shot competition",
        "Triple jump",
        "Truck racing",
        "Trugo",
        "Tug-o-war",
        "Tumbling",
        "Twenty20",
        "Ultimate",
        "Ultralight aviation",
        "Ultramarathon",
        "Underwater cycling",
        "Underwater football",
        "Underwater hockey",
        "Underwater ice hockey",
        "Underwater orienteering",
        "Underwater photography",
        "Underwater rugby",
        "Underwater target shooting",
        "Underwater wrestling",
        "Uneven bars",
        "Unicycle basketball",
        "Unicycle hockey",
        "Unicycle trials",
        "Unicycle",
        "Unicycling",
        "Universal football",
        "Uppies and Downies",
        "Urban Golf",
        "Vajra-mushti",
        "Vale tudo",
        "Valencian frontó",
        "Valencian pilota",
        "Varzesh-e Pahlavani",
        "Vault",
        "Vigoro",
        "Vintage racing",
        "Volata",
        "Volleyball",
        "Vovinam",
        "Wakeboarding",
        "Wakesurfing",
        "Walking",
        "Wall game",
        "Wall-and-ball",
        "Wallball",
        "Wallyball",
        "Water basketball",
        "Water polo",
        "Water volleyball",
        "Waymarking",
        "Weightlifting",
        "Western pleasure",
        "Wheelchair basketball",
        "Wheelchair racing",
        "Wheelchair rugby league",
        "Wheelstand competition",
        "White water rafting",
        "Whitewater kayaking",
        "Wife-carrying",
        "Wiffleball",
        "Windsurfing",
        "Wing Chun",
        "Wingsuit flying",
        "Wireball",
        "Woggabaliri",
        "Wolf hunting",
        "Women's lacrosse",
        "Wood chopping",
        "Wood splitting",
        "Woodball",
        "Woodsman",
        "Wrestling",
        "Wushu",
        "Xare",
        "Xiangqi",
        "Xing Yi Quan",
        "Yak polo",
        "Yağlı Güreş",
        "Yoyoing",
        "Yubi lakpi",
        "Yukigassen",
        "Zen Bu Kan Kempo",
        "Zourkhaneh"
    ]
}